// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Cadastro_usuario', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Cadastro_usuario', async function() {
    await driver.get("http://publicazo.insprak.com/sign_in")
    await driver.manage().window().setRect({ width: 1382, height: 736 })
    await driver.findElement(By.linkText("Cadastre-se")).click()
    await driver.findElement(By.id("user_fullname")).sendKeys("antonio")
    await driver.findElement(By.id("user_email")).sendKeys("antonio@gmail.com")
    await driver.findElement(By.id("user_password")).sendKeys("123456")
    await driver.findElement(By.id("user_password_confirmation")).sendKeys("123456")
    await driver.findElement(By.name("commit")).click()
    assert(await driver.findElement(By.css(".toast-message")).getText() == "Bem-vindo! Você se registrou com sucesso.")
  })
})
