// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Entrar_no_sistema2', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Entrar_no_sistema2', async function() {
    await driver.get("http://publicazo.insprak.com/")
    await driver.manage().window().setRect({ width: 1382, height: 736 })
    await driver.findElement(By.css(".panel-heading > a > img")).click()
    await driver.findElement(By.css(".img-circle")).click()
    await driver.findElement(By.linkText("Sair")).click()
    assert(await driver.findElement(By.css(".toast-message")).getText() == "Saiu com sucesso.")
    await driver.findElement(By.linkText("Entrar")).click()
    await driver.findElement(By.id("user_email")).click()
    await driver.findElement(By.id("user_email")).sendKeys("antonio@gmail.com")
    await driver.findElement(By.id("user_password")).click()
    await driver.findElement(By.id("user_password")).sendKeys("123456")
    await driver.findElement(By.name("commit")).click()
    assert(await driver.findElement(By.css(".toast-message")).getText() == "Logado com sucesso.")
    await driver.findElement(By.css(".panel-heading > a > img")).click()
  })
})
